### ISSUE TITLE
Fetch the Chain ID from a PDB

### ISSUE THREAD

**Issue by tubiana** [reuter-group/peprmint-web#2]
New possible feature / improvment: fetching a chain directly from the PDBID example: `2codA` will fetch only the chain `A` from the PDB `2cod`

**Comment by Ginko-X** [comment]
The new feature in the latest release V1.1 now offers an alternative way to calculate on only  interested chains: instead of just downloading the interested chains, the user can now select any interested elements (chains, plus residues, domains, etc.) through Mol* to perform the analysis

For example: select some residues:
<img width="438" alt="图片" src="https://user-images.githubusercontent.com/5687628/123812414-597e4780-d8f4-11eb-8b2b-881af761fb4b.png">

then tick the boxes:
<img width="786" alt="图片" src="https://user-images.githubusercontent.com/5687628/123812676-91858a80-d8f4-11eb-8568-85c9cc7fb98c.png">


I hope this alternative works out well and you will like it 😊
